### ISSUE TITLE
Add documentation on how to install project from source and run test cases

### ISSUE THREAD

**Issue by dauTT** [ontio/ontology-go-sdk#89]
I am not able to install correctly the project and run the test cases. I did as follow:

1) `glide update`
2) `go test ./..`

and got the following error message:

```go
--- FAIL: TestOntId_RegIDWithPublicKey (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8ff719]

goroutine 5 [running]:
testing.tRunner.func1(0xc0000e0300)
	/usr/local/go/src/testing/testing.go:830 +0x388
panic(0x98b2a0, 0xf06250)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/ontio/ontology-go-sdk.(*Wallet).NewIdentity(0x0, 0x10212, 0xece31c, 0x6, 0x6, 0xc0000b0d10, 0x4ecefd, 0xc05df0)
	/home/dau/workspace/go/src/github.com/ontio/ontology-go-sdk/wallet.go:450 +0x29
github.com/ontio/ontology-go-sdk.(*Wallet).NewDefaultSettingIdentity(...)
	/home/dau/workspace/go/src/github.com/ontio/ontology-go-sdk/wallet.go:472
github.com/ontio/ontology-go-sdk.TestOntId_RegIDWithPublicKey(0xc0000e0300)
	/home/dau/workspace/go/src/github.com/ontio/ontology-go-sdk/native_contract_test.go:12 +0x70
testing.tRunner(0xc0000e0300, 0xa5f0d0)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x357
FAIL	github.com/ontio/ontology-go-sdk	0.008s
?   	github.com/ontio/ontology-go-sdk/bip44	[no test files]
?   	github.com/ontio/ontology-go-sdk/client	[no test files]
?   	github.com/ontio/ontology-go-sdk/common	[no test files]
--- FAIL: TestOep4 (0.85s)
    oep4_test.go:59: open ../../wallet.json: no such file or directory
FAIL
FAIL	github.com/ontio/ontology-go-sdk/oep4	0.855s
?   	github.com/ontio/ontology-go-sdk/test	[no test files]
?   	github.com/ontio/ontology-go-sdk/utils	[no test files]



```

**Comment by lucas7788** [comment]
this error is due to the fact that some variables are not initialized. I will submit a pr to fix it. you can use go-sdk and ignore this error. and some testing interact with chain need you start ontology.
@dauTT
